add_newline = false
prompt_order = [
  "username",
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "jobs",
  "character"
]

[username]
show_always = true

[directory]
truncation_length = 10
truncate_to_repo = false

[character]
symbol = "➜"
